version: "3.9"
services:
  redis:
    image: redis:7
    container_name: krivz-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
  # bot:
  #   image: krivzbot:latest
  #   container_name: krivz-bot
  #   restart: always
  #   depends_on:
  #     - redis
  #   environment:
  #     TOKEN: ${TOKEN}
  #     REDIS_URL: redis://redis:6379
  # frontend:
  #   image: eva-frontend:latest
  #   container_name: eva-frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #     SECRET_KEY: ${SECRET_KEY}
